apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test2
  annotations:
    github.com/project-slug: gaikwadgaurav12495/test2
spec:
  type: other
  lifecycle: unknown
  owner: dev-hub-team
